version: '3.9'

services:
  php:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
        - "8000:8000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "laravel"
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"